### ISSUE TITLE
Optimum Value and Optimum Position of f24 are not correct

### ISSUE THREAD

**Issue by HaiAu2501** [Danial-Yazdani/GNBG_Instances.Python#1]
Dear Danial Yazdani,

I hope this message finds you well. I am reaching out to discuss a potential issue I've encountered with the data provided for the function f24 in your GitHub repository. Upon conducting my own analysis, I've come to believe that the optimum value and its corresponding position for this function, as presented in your documentation, may not accurately reflect the most optimal solution.

In my research, I have discovered a specific point where the function's value is significantly lower than the optimum value currently listed in your repository. This leads me to believe that there might be an alternative solution that offers a more optimal outcome.

I am prepared to share a vector of values that I used in my analysis, which I hope you will find useful for recalculating the function's optimum value and position. I believe this collaborative effort can enhance the accuracy and utility of the data for all users of your repository.

`x = [-13.27665639, 35.25206117, -79.98209601, -31.62663192, -56.51875815, -65.22631806, -50.19875005, -24.71038907, -16.51685608, 6.21096804, -12.92854709, 29.63507158, -47.2876304, 60.49839933, -75.61820568, 27.27442649, -13.2304883, 9.39034222, -57.53796309, -48.30403905, 48.11902222, 74.9212996, -29.85235956, 30.77117991, 60.22223297, 63.13701512, -66.39289698, -73.75156193, -52.82728168, 60.50286696]`

The value of f24 at this point is `-99.84769937697986` lower than your optimum value `-98.90165316616695`.

Thank you for considering this information. I look forward to any discussion this might prompt and am eager to hear your perspective on my findings.

Best regards,
HaiAu.

**Comment by Danial-Yazdani** [comment]
Dear Hai Au,

Thank you for reaching out and for your detailed analysis of the function f24 in our GitHub repository. I appreciate your effort in identifying this issue.

I have reviewed the issue and corrected the parameter settings for this instance. Please download the updated version of f24.mat from the repository. The new optimum value has been set to -100.

Could you please check the updated instance and confirm whether it resolves the issue? Your feedback is invaluable to ensuring the accuracy and reliability of our data.

Thank you once again for your collaboration.

Best regards, 

Danial
